sequenceDiagram
    participant browser
    participant server
    
    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    server-->>browser: The server responds to the request with status code 201 created
    deactivate server
    
    Note right of browser: The browser The request is directed to the new_note_spa address, is of type POST, and contains a new note in JSON format, which includes both content and a timestamp.
